---

postgresql_repo: "debian-ubuntu-postgresql-remote"
postgresql_keyring: "ACCC4CF8.asc"
postgresql_keyring_path: "/etc/apt/keyrings/{{ postgresql_keyring }}"

postgresql_version: "13"
postgresql_base_dir: "/etc/postgresql"
postgresql_data_dir: "{{ postgresql_base_dir }}/{{ postgresql_version }}/main"
postgresql_bin_dir: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
postgresql_replica_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"

# apply on both (master, slave)
postgresql_mode: master
postgresql_master_host: "{{ inventory_hostname }}"
postgresql_password: "StrongPassword"

# configuration
postgresql_listen_address: "*"
postgresql_port: "5432"
postgresql_max_connections: "400"
postgresql_shared_buffers: "2048MB"
postgresql_work_mem: "12MB"
postgresql_maintenance_work_mem: "320MB"
postgresql_effecitve_cache_size: "6GB"
postgresql_effective_io_concurrency: "300"
postgresql_max_parallel_workers: "16"
postgresql_max_parallel_workers_per_gather: "8"
postgresql_max_parallel_maintenance_workers: "8"
postgresql_max_worker_processes: "16"
postgresql_checkpoint_completion_target: "0.9"
postgresql_checkpoint_timeout: "15min"
postgresql_default_statistics_target: "100"
postgresql_random_page_cost: "2"
postgresql_huge_pages: "try"
postgresql_wal_level: "replica"
postgresql_max_wal_size: "2GB"
postgresql_min_wal_size: "1GB"
postgresql_max_wal_senders: "10"
postgresql_wal_keep_segments: "100"
postgresql_wal_sender_timeout: "60s"
postgresql_hot_standby: "on"
postgresql_max_standby_archive_delay: "900s"
postgresql_max_standby_streaming_delay: "900s"
postgresql_seq_page_cost: "0.7"
postgresql_wal_receiver_status_interval: "10s"
postgresql_hot_standby_feedback: "on"
postgresql_wal_receiver_timeout: "60s"
postgresql_wal_retrieve_retry_interval: "5s"
postgresql_wal_compression: "off"
postgresql_wal_buffers: "1MB"
postgresql_bgwriter_delay: "100ms"
postgresql_log_directory: "/var/log/postgresql"
postgresql_log_filename: "postgresql.log"
postgresql_log_truncate_on_rotation: "on"
postgresql_log_rotation_age: "3d"
postgresql_log_rotation_size: "512MB"
postgresql_log_min_messages: "warning"
postgresql_log_min_error_statement: "error"
postgresql_log_checkpoints: "off"
postgresql_log_connections: "off"
postgresql_log_disconnections: "off"
postgresql_log_duration: "off"
postgresql_log_line_prefix: "%t <%d %u %r> %%"
postgresql_log_lock_waits: "on"
postgresql_log_statement: "mod"
postgresql_log_replication_commands: "off"
postgresql_log_timezone: "Asia/Tbilisi"
postgresql_log_min_duration_statement: "10s"

##Sync replica
postgresql_synchronous_commit: "local"
postgresql_synchronous_standby_names: '*'
