galaxy_info:
  author: Giorgi Katcharava, Mate Gogiberidze, Aleksandre Kvaichadze, Nika Kostava, Saba Sakvarelidze, Davit Gogritchiani, Davit Samadashvili
  description: Provisions PostgreSQL master/slave streaming replication cluster with hot standby.

  min_ansible_version: 2.9

  platforms:
  - name: Ubuntu
    versions:
    - 22.04