---

- name: daemon reload
  systemd:
    daemon_reload: yes

- name: test nginx
  shell: nginx -t

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
