---
- name: delete metrics-server
  kubernetes.core.helm:
    name: "{{ k8s_metrics_server.name }}"
    chart_ref: metrics-server/metrics-server
    release_name: "{{ k8s_metrics_server.name }}"
    release_namespace: "{{ k8s_metrics_server.namespace }}"
    update_repo_cache: true
    state: "{{ k8s_metrics_server_state }}"
    release_state: "{{ k8s_metrics_server_state }}"
    wait: true
    kubeconfig: ~/.kube/config
