---
- hosts: localhost
  roles:
    - argocd
  environment:
    K8S_AUTH_KUBECONFIG: ~/.kube/config
  vars:
    k8s_argocd_admin: true
    k8s_argocd_url: https://argocd.example.com
    k8s_argocd:
      namespace: argocd
      policy:
        admins:
          - Admins
        readonlies: []
      ingress:
        spec:
          host: argocd.example.com
          tls:
            secret: star-example-com
    k8s_argocd_ldap:
      name: dc01.example.com
      host: dc01.example.com:389
      usersearch:
        basedn: DC=example,DC=com
        emailattr: userPrincipalName
      groupsearch: 
        basedn: DC=example,DC=com
    k8s_argocd_dex_ldap_bindpw: "StrongPassword"

    k8s_argocd_dex_ldap_binddn: "StrongPassword"