galaxy_info:
  author: Giorgi Katcharava, Mate Gogiberidze, Aleksandre Kvaichadze, Nika Kostava, Saba Sakvarelidze, Davit Gogritchiani, Davit Samadashvili
  description: This Ansible role installs and configures a Kubernetes cluster on Debian-based systems. It supports configuring master and worker nodes, as well as different network providers.

  min_ansible_version: 2.9

  platforms:
  - name: Ubuntu
    versions:
    - 22.04
