---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app: grafana
spec:
  project: grafana
  source:
    chart: grafana
    repoURL: 'https://gitlab.example.com/api/v4/projects/69/packages/helm/stable'
    targetRevision: 47.3.0
    helm:
      valueFiles:
        - values.yaml
      releaseName: grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true